name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC
    - cron: '0 9 * * *'   # 09:00 UTC
    - cron: '0 17 * * *'  # 17:00 UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -sSf https://your-streamlit-app-url.streamlit.app || echo "App ping failed"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup git user
        run: |
          git config user.name "MathieuBK"
          git config user.email "MathieuBK@users.noreply.github.com"

      - name: Set remote URL with token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest main
        run: git pull origin main --rebase

      - name: Update keep_alive.txt with current timestamp
        run: |
          echo "Last keep alive: $(date -u)" > keep_alive.txt

      - name: Add and commit update
        run: |
          git add keep_alive.txt
          git commit -m "Keep alive update $(date -u)" || echo "No changes to commit"

      - name: Push to main branch
        run: git push origin main --force
